  replicaCount: 3

  image:
    repository:my-app
    tag:latest
    pullPolicy:Always
  service:
    type:LoadBalancer
    port:80
  resources:
    limits:
      cpu:500m
      memory:512Mi
    requests:
      cpu:200m
      memory:256Mi
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
